# Generated by Django 5.0.3 on 2024-03-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
